### ISSUE TITLE
DACPAC Build step not working

### ISSUE THREAD

**Issue by ashishmg-gds** [santiagxf/synapse-cicd#3]
@santiagxf 
Hi, Im trying to replicate your solution in one of my projects. But  unfortunately Im getting below error :

`/usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/3.0.0-release.110/Microsoft.Data.Tools.Schema.SqlTasks.targets(1216,24): error MSB4057: The target "BuildOnlySettings" does not exist in the project`

Do you have any idea what this is about. My first guess was if its dotnet related

**Comment by santiagxf** [comment]
Looks like the project file (*.sqlproj) has the wrong target configured. Compare it with the sample one for AdventureWorks which has “build” as target instead and let me know.

**Comment by santiagxf** [comment]
Closing the issue due to inactivity.
